title: Kelvin and Hobbes
author: Kelvin Adams
description: > # this means to ignore newlines until "baseurl:"
   Hello there! I'm a recovering mechanical engineer interested
   in systems and data analytics. When I'm not nerding out on data,
   you can find me building worlds and writing adventures for D&D. 
   Or snuggling my dogs. Yep...mostly the dog thing...

# social links
twitter_username: kelvin_adams
github_username:  kelvinadams # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
